{
 "title": "WESAD_Emotional-State-Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Monitoring and Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Input",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Emotional State",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Subject Information ",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Electrodermal Scan vs Emotional States : Sensor Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Amused State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_eda, w_eda FROM \"Sensor_Input_amused\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Stressed State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_eda, w_eda FROM \"Sensor_Input\" LIMIT 501 "
    }
   ]
  },
  {
   "title": "Meditative State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_eda, w_eda FROM \"Sensor_Input_meditative\" LIMIT 501 "
    }
   ]
  },
  {
   "title": "Chest and Wrist Temperature vs Emotional State : Sensor Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Amused State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_temp, w_temp FROM \"Sensor_Input_amused\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Stressed State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_temp, w_temp FROM \"Sensor_Input\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Meditative State",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, label, c_temp, w_temp FROM \"Sensor_Input_meditative\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Chest Movement vs. Emotional States : Sensor Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Amused state",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Sensor_Input_amused\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Stressed state",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Sensor_Input\" LIMIT 500 "
    }
   ]
  },
  {
   "title": "Meditative State",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT sample_id, c_acc_z FROM \"Sensor_Input_meditative\" LIMIT 500 "
    }
   ]
  }
 ]
}